# This rule is not used by the project k8s-opreator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the myservice.cyk.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-opreator
    app.kubernetes.io/managed-by: kustomize
  name: apiservice-editor-role
rules:
- apiGroups:
  - myservice.cyk.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - myservice.cyk.io
  resources:
  - apiservices/status
  verbs:
  - get
